### ISSUE TITLE
How not to use SockJS

### ISSUE THREAD

**Issue by Glamdring** [rstoyanchev/spring-websocket-portfolio#14]
I don't need to use SockJS - I would just like to use a regular websocket. Stomp provides: Stomp.client("ws://<host>:<port>/endpoint"). However, that doesn't seem to work with this example. Can it work, and how to make it work like that. 
Probably it would be nice ot have a page without SockJS.

**Comment by cooniur** [comment]
So what is the solution? I tried to use SockJsClient to connect to Slack's Real Time Messaging API WebSocket and it automatically sends a "server info" API call to Slack's websocket server, which fails the connection with 400 bad request. How can I use WebSocket in Spring without anything like SockJS, Stomp, etc.? I just want to connect to Slack's websocket and listen to its events.

Thanks!

**Comment by cooniur** [comment]
In Spring 4.2, just use the `StandardWebSocketClient`, and handle the message by implementing `WebSocketHandler` interface.

Something like:

    def client = new StandardWebSocketClient()
    client.doHandshake(new MyWebSocketHandler(), rtmWsUrl)

    private static class MyWebSocketHandler implements WebSocketHandler {
        ....
    }

**Comment by rstoyanchev** [comment]
Indeed, and the [chapter in the reference](http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/websocket.html) documentation is organized starting with a sub-section on WebSocket followed by SockJS and then STOMP.

**Comment by yovinn** [comment]
7455

**Comment by yovinn** [comment]
i can not understand your mean!

**Comment by thoslin** [comment]
I had the same issue with OP. The scenario is that I tried to connect to spring websocket from iOS, however I didn't find any usable Stomp library that supports sockjs. So I tried to use Stomp without sockjs. Per the documentation https://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-intro.

> Or  if connecting via WebSocket (without SockJS):

```
var socket = new WebSocket("/spring-websocket-portfolio/portfolio");
var stompClient = Stomp.over(socket);

stompClient.connect({}, function(frame) {
}
```

I removed the with-sockjs line from my configuration and tested it in chrome dev tools. However it didn't work. The error is URL invalid. Then I used the URL "ws://domain/spring-websocket-portfolio/portfolio", it then gave me 400 Bad Request.

Am I missing something here?

**Comment by acrive82** [comment]
Removing .withSockJS() 

`Caused by: java.lang.IllegalStateException: No suitable default RequestUpgradeStrategy found`

**Comment by rstoyanchev** [comment]
> So without sockjs, which url should I connect to?

The same.

> No suitable default RequestUpgradeStrategy found

Old server version perhaps?

**Comment by acrive82** [comment]
I use SpringBoot 1.5.2 with tomcat starter.  I'm try to figure out why this happens : [link](http://stackoverflow.com/questions/43239624/sockjs-stomp-springboot-issue)

**Comment by rstoyanchev** [comment]
That links shows a different error than the "RequestUpgradStrategy not found".

**Comment by thoslin** [comment]
@rstoyanchev it's not working for me. I tried:
```
var ws = new WebSocket("ws://127.0.0.1:9200/spring-websocket-portfolio/portfolio")
```
It gave the error:
> WebSocket connection to 'ws://127.0.0.1:9200/spring-websocket-portfolio/portfolio' failed: Error during WebSocket handshake: Unexpected response code: 400

while if I tried
```
var ws = new WebSocket("ws://127.0.0.1:9200/spring-websocket-portfolio/portfolio/websocket")
```
It then gave the error

> WebSocket connection to 'ws://127.0.0.1:9200/spring-websocket-portfolio/portfolio/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by rstoyanchev** [comment]
If SockJS is turned off there is no point in trying `/{endpoint}/websocket` since that's a URL structure only supported with SockJS.

Well 400 means bad input. Look further. Response headers, DEBUG logging for `org.springframework.web`, step through with debugger if needed. You're missing something basic.

**Comment by nadirvishun** [comment]
this answer: [Spring boot Websocket without SockJS](https://stackoverflow.com/a/68076180/7197770)
registry two same name endpoint: 
```java

        @Override
        public void registerStompEndpoints(StompEndpointRegistry registry)
        {
                // This will allow you to use ws://localhost:8080/test to establish websocket connection
                registry.addEndpoint("/test");
                // This will allow you to use http://localhost:8080/test to establish websocket connection
                registry.addEndpoint("/test").withSockJS(); 
        }
```
