### ISSUE TITLE
Handling client disconnects (Stomp + SockJS + RabbitMQ)

### ISSUE THREAD

**Issue by jmzD** [rstoyanchev/spring-websocket-portfolio#20]
I would like to publish to a topic when a client disconnect is detected in order to update other users that are subscribed to the topic.  However, I am running into issues using both WebSocketMessageBrokerConfigurationSupport and WebSocketConfigurer at the same time.  When I add a custom handler (via WebSocketConfigurer.registerWebSocketHandlers) none of the the lifecycle events seem to fire.  Ultimately, it seems that my custom handler is being overridden by stomp, as stomp functionality works perfectly fine.  

Please note: I require stomp with sockjs and the ws handler and stomp are mapped to the same endpoint (ex: "/comp") 

I could be missing something, but it seems like this should be possible as the LoggingWebSocketHandlerDecorator logs to file in afterConnectionClosed when using a message broker and the stomp sub protocol.  Would you please point me in the right direction?

Thank you for your time.

**Comment by gryphonest** [comment]
@jmzD  hi, can you tell me how to handle?
