### ISSUE TITLE
Can I use more than one broker relay, with something else than STOMP?

### ISSUE THREAD

**Issue by knockoutuser** [rstoyanchev/spring-websocket-portfolio#47]
From what I see from the application and the Spring code, seems you can only register one broker relay, and it must be a STOMP broker relay.

Can I register more than one? Must I always use STOMP?

**Comment by GADNT** [comment]
Hi @rstoyanchev 

Related to your last comment. Do you know that the approach you mentioned have been implemented? 
If yes or do you know , can you point to me an example that take this approach with having more than one broker available ?

Thank you
Gabriel

**Comment by rstoyanchev** [comment]
Unfortunately no, see [here](https://jira.spring.io/browse/SPR-12452) and also [here](https://github.com/reactor/reactor/issues/412).
