### ISSUE TITLE
Question: Spring Websocket intercept and transform message before serialization

### ISSUE THREAD

**Issue by tongc** [rstoyanchev/spring-websocket-portfolio#58]
So at the moment I have a subclass of ChannelInterceptorAdapter to intercept the messages before sending to client. However,

public Message<?> preSend(Message<?> message, MessageChannel channel)
The message.payload here is already serialized so it is hard to do any manipulations. I noticed that the serialization is done inside

AbstractMessageSendingTemplate
Message<?> message = doConvert(payload, headers, postProcessor);
So my question is that is there a way to intercept the message before it is serialized so that we can manipulate the message before sending out.

What I can think of is to register a messageConverter (org.springframework.messaging.converter.MessageConverter) that does nothing, and only convert after interceptor processed it. But this doesn't feel like a very clean solution.

I also noticed that there is MessageTransformingChannelInterceptor for transforming the msg but is deprecated. I don't get the idea of transforming the msg after it is converted by MessageConverter

**Comment by rstoyanchev** [comment]
There is no interception point for that right now. For the MessageConverter approach, [we currently use](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/simp/config/AbstractMessageBrokerConfiguration.java#L340) a CompositionMessageConverter already. I suppose you could wrap that once more.
