### ISSUE TITLE
How to acknowledge message?

### ISSUE THREAD

**Issue by achmadns** [rstoyanchev/spring-websocket-portfolio#68]
Dear @rstoyanchev , could you please share how to acknowledge a message?

I have set the stomp headers when subscribing.

```java
final StompHeaders headers = new StompHeaders();
headers.setDestination(destination);
headers.setAck("client");
session.subscribe(headers, new StompSessionHandlerAdapter(){});
```

but when I try to ack the message, there is no method for it on [StompSession](https://github.com/spring-projects/spring-framework/blob/v4.2.6.RELEASE/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompSession.java) interface. Is it by design?

Thank you.

**Comment by achmadns** [comment]
I checked out (spring-messaging 4.3.0.RELEASE)[https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompSession.java]. It already there but still on not general RELEASE of Spring Boot. Waiting to be finished up.

**Comment by rstoyanchev** [comment]
Yes it's in 4.3 https://jira.spring.io/browse/SPR-14208.
