### ISSUE TITLE
Websocket Client/ Server side issue.

### ISSUE THREAD

**Issue by amankachhal99** [rstoyanchev/spring-websocket-portfolio#73]
I Am using spring 4.1.1, stomp, sockjs for websocket connection. 
1. i have observed that my websocket connection keeps on breaking from time to time, though i have written a reconnect mechanism but i want to know why connection breaks. I get the logs like below on browser console: 
<<< ERROR
message:Connection to broker closed.
content-length:0

stomp.js?ver=1.2.06:130 >>> UNSUBSCRIBE
id:sub-0

stomp.js?ver=1.2.06:130 >>> UNSUBSCRIBE
id:sub-1

stomp.js?ver=1.2.06:130 >>> UNSUBSCRIBE
id:sub-2

stomp.js?ver=1.2.06:130 >>> UNSUBSCRIBE
id:sub-3

stomp.js?ver=1.2.06:130 >>> UNSUBSCRIBE
id:sub-4

2. Also while initiating the connection i get failure for first 2, 3 attempts. Logs are:

_WebSocket connection to 'ws://localhost:7001/tims-web/wsEndPoint/587/tfmusptg/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
SockJS.websocket @ sockjs.js?ver=1.2.06:1213
SockJS._try_next_protocol @ sockjs.js?ver=1.2.06:1150
SockJS._didClose @ sockjs.js?ver=1.2.06:1058
SockJS.that._ir.onfinish @ sockjs.js?ver=1.2.06:984
EventEmitter.emit @ sockjs.js?ver=1.2.06:148
InfoReceiver.doXhr.xo.onfinish @ sockjs.js?ver=1.2.06:1948
EventEmitter.emit @ sockjs.js?ver=1.2.06:148
AbstractXHRObject._start.that.xhr.onreadystatechange @ sockjs.js?ver=1.2.06:801_

3. Also below logs keep on coming from time to time:

POST http://localhost:7001/tims-web/wsEndPoint/587/5pu63ctc/xhr_send 500 (Internal Server Error)
AbstractXHRObject._start @ sockjs.js?ver=1.2.06:807
(anonymous) @ sockjs.js?ver=1.2.06:834
sockjs.js?ver=1.2.06:1040 

Uncaught Error: INVALID_STATE_ERR
    at SockJS._didClose (sockjs.js?ver=1.2.06:1040)
    at sockjs.js?ver=1.2.06:1307
    at utils.XHRCorsObject.xo.onfinish (sockjs.js?ver=1.2.06:1389)
    at utils.XHRCorsObject.EventEmitter.emit (sockjs.js?ver=1.2.06:148)
    at XMLHttpRequest.AbstractXHRObject._start.that.xhr.onreadystatechange (sockjs.js?ver=1.2.06:801)
SockJS._didClose @ sockjs.js?ver=1.2.06:1040
(anonymous) @ sockjs.js?ver=1.2.06:1307
xo.onfinish @ sockjs.js?ver=1.2.06:1389
EventEmitter.emit @ sockjs.js?ver=1.2.06:148
AbstractXHRObject._start.that.xhr.onreadystatechange @ sockjs.js?ver=1.2.06:801
stomp.js?ver=1.2.06:130 

Opening Web Socket...

sockjs.js?ver=1.2.06:1213 WebSocket connection to 'ws://localhost:7001/tims-web/wsEndPoint/481/7w_se_6_/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
SockJS.websocket @ sockjs.js?ver=1.2.06:1213
SockJS._try_next_protocol @ sockjs.js?ver=1.2.06:1150
SockJS._didClose @ sockjs.js?ver=1.2.06:1058
SockJS.that._ir.onfinish @ sockjs.js?ver=1.2.06:984
EventEmitter.emit @ sockjs.js?ver=1.2.06:148
InfoReceiver.doXhr.xo.onfinish @ sockjs.js?ver=1.2.06:1948
EventEmitter.emit @ sockjs.js?ver=1.2.06:148
AbstractXHRObject._start.that.xhr.onreadystatechange @ sockjs.js?ver=1.2.06:801
stomp.js?ver=1.2.06:130 Web Socket Opened...

Please help !!!

**Comment by rstoyanchev** [comment]
You should be on the latest 4.3.x (4.1.x is not a supported branch). Even this is not a place for general questions nor the issue tracker for the Spring Framework.
