### ISSUE TITLE
Spring websocket multiple tomcat servers

### ISSUE THREAD

**Issue by mi13chael** [rstoyanchev/spring-websocket-portfolio#82]
Hi Rossen, 
   Learned lot in your comment in stackoverflow, and My team have implemented the Websocket on STOMP broker in RocketMQ in multiple tomcat servers , which is working well.
   Now we have new requirement , some mobile devices have to connect to the servers through WebSocket without STOMP , also have to implement the distributed user sessions , Could you please give some ideas ?
   Thanks in advance.
Michael

**Comment by rstoyanchev** [comment]
@mi13chael you could look at Spring Session https://docs.spring.io/spring-session/docs/current/reference/html5/.
